spring:
  application:
    name: fitness-tracker-api-spring-boot
  datasource:
    url: jdbc:h2:file:../fitness_db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
      data-locations: 
          - optional:classpath:data.sql
          - optional:classpath:fixtures.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true 
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB 

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.hibernate.orm.jdbc.bind: info

jwt:
  secret: MySuperS3cr37JWTSecret
  expiration: 86400
  issuer: dev.shendriks.fitnesstrackerapi
