### POST activity
POST {{base_url}}/activities
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "activityType": "running",
  "duration": 950,
  "calories": 320
}

### GET activities
GET {{base_url}}/activities
Authorization: Bearer {{access_token}}
