### POST developer signup
POST {{base_url}}/developers/signup
Content-Type: application/json

{
  "email": "foo@bar.baz",
  "password": "12345"
}

### GET developer by id
GET {{base_url}}/developers/1
Content-Type: application/json
Authorization: Basic {{basic_auth}}

###