### POST user signup
POST {{base_url}}/users/signup
Content-Type: application/json

{
  "email": "foo@bar.baz",
  "password": "12345"
}

### GET user by id
GET {{base_url}}/users/1
Content-Type: application/json
Authorization: Basic {{basic_auth}}

###