spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

jwt:
  secret: test-token-secret
  expiration: 30
  issuer: test-fitnesstrackerapi
